### ISSUE TITLE
Consider using queue interprop as abstraction for queues

### ISSUE THREAD

**Issue by makasim** [nuwber/rabbitevents#10]
Hello!

Please look at https://github.com/queue-interop/queue-interop project. Using interfaces from it allows us reuse some implementations like enqueue, which supports a lot of transports. You can outsource some code

**Comment by masterjus** [comment]
Thanks, @makasim 
I'm using your lib as a basement to communicate with rabbitmq. What exactly do you mean?

**Comment by makasim** [comment]
Sorry, I've not noticed it. closing.
