### ISSUE TITLE
Question about graceful restarting.

### ISSUE THREAD

**Issue by Xachman** [nuwber/rabbitevents#103]
Is there a way to wait for a message to be finished processing before stopping/restarting the Listeners?

**Comment by masterjus** [comment]
It depends only on the way how do you run listeners. Unfortunately, can't be run in the daemon mode itself, only with a tool like supervisord. 

A Listener should finish the current job if you stop daemon with SIGTERM https://github.com/nuwber/rabbitevents/blob/7.x/src/RabbitEvents/Listener/Worker.php#L226

**Comment by Xachman** [comment]
Ok thats what I thought I am throwing together a bash script to do this.  And I am using kill and basically looping thru all the jobs with it when docker sends its signal.  But let me make sure that the script itself isnt one of the jobs somehow.

**Comment by Xachman** [comment]
Ok I think my issue is I wasn't waiting after running the kill command on the job id. 

```
        for job in `jobs -p`
        do
            kill -s SIGTERM $job
            wait $job
        done
```
Basically I am using this and I didn't have the wait part there. I am still working on this but I think its gracefully stopping now.

**Comment by Xachman** [comment]
Ok to test this out I made my listener process do a sleep for 60 seconds but for some reason when I restart the container the listeners stop "gracefully" but clearly 60 seconds has not passed. Im not sure if somehow that SIGTERM is getting passed along and quitting the sleep process yet tho.

**Comment by Xachman** [comment]
As I thought sleep somehow still gets canceled.  And if you want to test this sort of thing with sleep you have to use this pattern:

```
        $left = sleep(60);
        while ($left > 0) {
            $left = sleep($left);
        }
```

Found the answer here https://stackoverflow.com/a/33652552

Im going to close thanks for responding.
