### ISSUE TITLE
PsrContext not instantiable

### ISSUE THREAD

**Issue by corradomatt** [nuwber/rabbitevents#12]
While playing with this library I've run into the following exception...

```
Illuminate\Contracts\Container\BindingResolutionException thrown with message "Target [Interop\Queue\PsrContext] is not instantiable while building [Nuwber\Events\BroadcastFactory]."
```

I've following the instructions on the README.md and done the following...

1. Installed the package with `composer require nuwber/rabbitevents`
2. Created `RabbitMQEventServiceProvider` that extends `Nuwber\Events\BroadcastEventServiceProvider`
3. Registered the following with my app service providers... ```\App\Providers\RabbitMQEventServiceProvider::class,
        \Enqueue\LaravelQueue\EnqueueServiceProvider::class,```
4. Setup the queue driver for `interop` and set it as the default.

This is version 5.5 of Laravel. Any ideas what I'm missing or what might be wrong?

**Comment by masterjus** [comment]
it is registering in https://github.com/nuwber/rabbitevents/blob/master/src/BroadcastEventServiceProvider.php#L60
Seems like you overriding `register` method and don't call `parent::register` in your RabbitMQEventServiceProvider.

**Comment by masterjus** [comment]
Closed as there's no answer
