### ISSUE TITLE
Target [Interop\Queue\PsrContext] is not instantiable while building [Nuwber\Events\BroadcastFactory].

### ISSUE THREAD

**Issue by seivad** [nuwber/rabbitevents#15]
Hey guys, I've got this error: 

```Target [Interop\Queue\PsrContext] is not instantiable while building [Nuwber\Events\BroadcastFactory].``` after following the installation instructions. 

I see this issue was closed off already without a provided fix. This is on a fresh project for testing purposes. 

It comes from the Helper:

```
function fire(string $event, array $payload)
    {
        app(BroadcastFactory::class)->send(
            app(MessageFactory::class)->make($event, $payload)
        );
    }
``` 
When going through the debugging in Laravel 5.

Also in the instructions it says there will be a console command of ```events:listen``` but this does not exist, did you mean ```queue:listen``` by any chance? 

I'd really like to try out this package if you could provide some ideas in how to resolve this issue?

**Comment by masterjus** [comment]
@seivad do you still have troubles?

**Comment by masterjus** [comment]
Close this issue as there's no answer

**Comment by masterjus** [comment]
Closed as there's no answer
