### ISSUE TITLE
queue in rabbit not create with queue:work command.

### ISSUE THREAD

**Issue by Spartaques** [nuwber/rabbitevents#19]
When i push some job to queue for example with default queue, i receive this error:

**local.ERROR: NOT_FOUND - no queue 'default' in vhost '/' {"exception":"[object] (PhpAmqpLib\\Exception\\AMQPProtocolChannelException(code: 404): NOT_FOUND - no queue 'default'** 

For some reason queue not created in rabbitmq when i try to listen to it. But when i use
php artisan rabbitevents:listen $eventname
all works correctly.

After this bug i switch to this package 
**https://github.com/vyuldashev/laravel-queue-rabbitmq**
that include only laravel queue in one server functionaty using laravel queue API and i saw that queue created automatically in rabbitmq. 

I fix this error by manually creating queue using rabbitmq manager. But if i understand correctly i shouldn't do this.

**Comment by masterjus** [comment]
If you switched to another package, why did you write this message here? I don't understand what do you want to fix.

**Comment by Spartaques** [comment]
@masterjus queue not created because it creates on message producing. Fixed)

**Comment by masterjus** [comment]
Ok
