### ISSUE TITLE
Question: Your application doesn't have any registered broadcast events.

### ISSUE THREAD

**Issue by eckelarsson** [nuwber/rabbitevents#22]
Hey,

I'm sorry to be asking or facing all these newbie errors, that are more question I think.
But if you have the time to help me figure out why my event listeners are not registering in the application.

I've registered in app/config.php a service provider that is called "RabbitMQEventServiceProvider"

That file looks like this

````
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Nuwber\Events\BroadcastEventServiceProvider;

class RabbitMQEventServiceProvider extends BroadcastEventServiceProvider
{
    protected $listen = [
        'events' => [
            'App\Listeners\EventLogger',
        ],
    ];
    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        //
        
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        //
        
    }
}
````

Then i have a simple listner
````
<?php

namespace App\Listeners;

use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;

class EventLogger
{
    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     *
     * @param  object  $event
     * @return void
     */
    public function handle(string $event, array $payload)
    {
        //
        log($event);
        log($payload);
    }
}
````

What am I missing?

Thank you.

**Comment by masterjus** [comment]
Your service provider rewrites methods `register` and `boot` which are registered commands and so on. Remove them or call parent methods

**Comment by eckelarsson** [comment]
Thank you, that did the trick! I removed the register and boot. Now I can see that the application register that listens. I see in RabbitMQ that application is connected and active.

But it seems that when I fire the event, i see that RabbitMQ receives the message but the EventLogger listener doesn't pick it up and like you can see log the event and payload in my log file. 

Is there something more I need to in the provider to make it work?

**Comment by masterjus** [comment]
Did you start to listen this event as it described here https://github.com/nuwber/rabbitevents#command-listen?

**Comment by eckelarsson** [comment]
Yes! And i see its running and connected to Rabbit.

**Comment by masterjus** [comment]
Do you have a repositories for your code? It's hard to troubleshoot without visualization.
Do you try to send and handle event in the same application?

**Comment by eckelarsson** [comment]
For now  yes, im sending and handle in the same application. I'll upload the repo so you can see.

**Comment by eckelarsson** [comment]
https://bitbucket.org/eriklarsson-velumi/rabbitmqtest/

**Comment by masterjus** [comment]
I've newer tested library this way as it not necessary. It may not work :-)

**Comment by eckelarsson** [comment]
Aha okey :) its supposed to work between applications so thats the goal, this is me just testing. Ill will do a real test between to application. 

Got it to work "ish" it recives sometimes and sometimes not. But that can do with that its not constructed in that way.

**Comment by masterjus** [comment]
where are you firing event?

**Comment by eckelarsson** [comment]
the router web.php

**Comment by eckelarsson** [comment]
Tried it between two applications now, and it works great!! Thanks for all your help man.

**Comment by masterjus** [comment]
![image](https://user-images.githubusercontent.com/464043/53250325-3cedf700-36cb-11e9-8729-c429cdf3ea1e.png)

**Comment by masterjus** [comment]
>> If you dont have any inputs on the code? 
don't understand what you mean

BTW I've just released the new version.

**Comment by eckelarsson** [comment]
Yeah, i saw that! Great with the new features!

I mean, if there anything in the setup that I've missed.

It worked in the same application, but it's inconsistent. If you send 10 events you receive about 6-7.

**Comment by masterjus** [comment]
Are there anything that still need to be resolved?
