### ISSUE TITLE
Support Laravel 6.0

### ISSUE THREAD

**Issue by rgergo67** [nuwber/rabbitevents#27]
Could you please support Laravel 6.0?

**Comment by masterjus** [comment]
there's the task in list https://github.com/nuwber/rabbitevents/projects/1#card-26204074.
To add support is not so easy because of some changes.
If you could do it fast, please make a pull request and I'll apply it.

**Comment by masterjus** [comment]
please try. If it's enough just to add it to supported versions list, I'll do it

**Comment by rgergo67** [comment]
The enqueue/laravel-queue dependency has illuminate/queue: ^5.6 dependency, I could not update that one, got some error back. I will make a request there too, unfortunately I am not experienced enough to help more. 

Just take your time, I appreciate your hard work, your package is a big help for us. Keep up!

**Comment by masterjus** [comment]
there's a new dependency to `laravel/helpers` in Laravel 6 and I have no idea how to keep 5th and 6th version without a new major version. But in this case, I'll need to support both versions in new features.

**Comment by andrew-nuwber** [comment]
No need to require `laravel/helpers` just replace all helpers with static classes calls

**Comment by masterjus** [comment]
https://packagist.org/packages/enqueue/laravel-queue requires illuminate/queue ^5.4

**Comment by masterjus** [comment]
Please use version https://github.com/nuwber/rabbitevents/releases/tag/v2.0.

I've tested this package in Laravel 5.8 application. If there will be any issues with Laravel 6, please let me know.
