### ISSUE TITLE
Do payloads have to be JSON?

### ISSUE THREAD

**Issue by Xachman** [nuwber/rabbitevents#56]
In the Queue\Job class it uses the payload function from \Illuminate\Queue\Jobs\Job.  This function returns json and if the payload in rabbitmq is not json it returns null.  When this happens you will get a too few arguments error on your listener classes handle function.  

If its expected that we will always be using json can we add that to the documentation?  Otherwise we should implement this so other none json data can be stored and passed along.

**Comment by masterjus** [comment]
@Xachman you're right, json is required format. I'll add this requirement to documentation and think how to validate payload.

**Comment by masterjus** [comment]
@Xachman one question: when you publish data, you need to pass a php array `publish` method and this methid converts an array to json inside. How it happened that nonjson data was published?

**Comment by Xachman** [comment]
The other service is not laravel.  I was just publishing messages for testing.  The frontend application is laravel and the backend will be python consuming messages from the laravel application and publishing other messages.  Knowing the expected format here is important so these 2 applications can communicate.

**Comment by masterjus** [comment]
OK. The package expects that messages are published and handled by their methods, so your flow didn't expected. 

Please suggest the best part in doc where I should add notice about format and I'll add it.

**Comment by Xachman** [comment]
I think in the listeners section it should be noted since this is where it applies and will fail. 
https://github.com/nuwber/rabbitevents#defining-listeners-  

In my tests what would happen is the payload was not even passed in if it was not json.  You get the 1 argument expected none passed in error. So its not really clear here what the expectation is of the Listener payload is just that it's usually an array.  Tho I cant see what case it would not be an array since it's using the type in the parameter.

**Comment by masterjus** [comment]
There's documentation upgrade. Is it clear?

**Comment by Xachman** [comment]
I think this definitely helps!  I think this information on how payloads are interpolated is beneficial even in a standard use case.        I'm not going to be too picky about this tho my project is working knowing that the expected format is json.

**Comment by masterjus** [comment]
Ok, thank you for your help. I close the issue.
