### ISSUE TITLE
sync or dummy driver for testing environment

### ISSUE THREAD

**Issue by colq2** [nuwber/rabbitevents#73]
Hello,
great package, thank you for this!

Is it possible to add something like a built in `sync` or `dummy` driver for testing environments?

All laravel internal have some 'local' drivers like array for cache, memory for database or sync for queues. It makes testing scenarios very easy, because you don't need to deploy external services like rabbitmq.

**Proposal:**

Add a dummy driver which takes an event and it does just nothing with it. It's important, that the `Listener::fake()` should still work.

A config could looks like 

```
    'connections' => [
        'rabbitmq' => [
             ...
        ],
        'testing' => [
            'driver' => 'dummy'
        ]
    ],
```

**Comment by masterjus** [comment]
Hi @colq2 

Thanks for your rate (Have you starred the package?).

This package was made to make possible a communication between different applications. That means that one app has implementation of publisher, another implements a Listener. I don't imagine how could it be implemented.

**Comment by masterjus** [comment]
how about a command like:
```
php artisan rabbitevents:publish --event=item.updated --payload='{"item": {"id": 234, "name": "Item1"}'
```

**Comment by masterjus** [comment]
No answer

**Comment by renepardon** [comment]
> Hi @colq2
> 
> Thanks for your rate
> 
> This package was made to make possible a communication between different applications. That means that one app has implementation of publisher, another implements a Listener. I don't imagine how could it be implemented.

It would indeed makes sense if you publish an event which would will also be consumed by the same application (publisher and listener)

Another use case is to check if an event was being dispatched. One can not use the Event::fake() method and Event::assertDispatched() because the nuwber/rabbitevents events work differently.

**Comment by renepardon** [comment]
@masterjus ?
