### ISSUE TITLE
ShouldBeUnique Support

### ISSUE THREAD

**Issue by zek** [nuwber/rabbitevents#74]
Hey there! 

Is it possible to use `ShouldBeUniqueUntilProcessing`, `ShouldBeUnique` interfaces with this package?

https://laravel.com/docs/8.x/queues#keeping-jobs-unique-until-processing-begins

**Comment by masterjus** [comment]
Hi @zek 
You mean that same event could be published from different sources at the same time?

**Comment by zek** [comment]
Actually no. I need to block tasks within the same group and make sure they processed in order. 
(Group key included in task data) 

Let me tell you my use case.

I have a microservice which collects data and pushes this data to rabbitmq and data handled by queue workers. There are 400 instances of this microservice.

For scaling purposes I have multiple queue workers on multiple machines. 
In my case task order is very important.
I'm afraid if task order may be mixed up.  
Right now I use cache lock feature and block task as following.

```
Cache::lock('group:'.$groupKey, 10)->block(...)
```

So multiple events may pushed at the same second or even milisecond and I need to make sure they're executed in order by multiple queue workers.

**Comment by masterjus** [comment]
The order issue is clear for me. And I still don't realise how to solve this without the scan of the full list of current tasks. It should be some dispatcher which will be the only point to return messages or so.
But this isn't the issue of the Uniqueness.

**Comment by masterjus** [comment]
I'm truly believe that the Rabbitevents works in FIFO principle. So if many listeners are listening to one queue messages will be handled in the right order.

**Comment by zek** [comment]
> I'm truly believe that the Rabbitevents works in FIFO principle. So if many listeners are listening to one queue messages will be handled in the right order.

Indeed but in my case each task within the same group must wait for previous tasks to be completed. 

I guess I mention wrong Interface, should be `WithoutOverlapping`.

https://laravel.com/docs/8.x/queues#preventing-job-overlaps

**Comment by zek** [comment]
Even `Cache::lock` doesn't solve my issue :/

I have 10 workers and have 2 events that queued at the same second with the same group key.

Event A (group X) queued at 16:14:46.7181 
Event B (group X) queued at 16:14:46.7237

I just need Event B waits for Event A to be completed. But in my case Event B processed before Event A.

**Comment by masterjus** [comment]
Close
