### ISSUE TITLE
Add option --message-ttl

### ISSUE THREAD

**Issue by masterjus** [nuwber/rabbitevents#90]
There's the option `--tries` which tells how many times a Message could be handled. But there's the problem if a Message becomes outdated. If there's still possible tries but a Message is already expired, it sould be skept and removed from a queue.

The `--message-life-time` (could be ranamed if necessary) should set the number of seconds in which a message should be handled.

**Comment by masterjus** [comment]
First of all, let's call it `--message-ttl`

**Comment by eugene-nuwber** [comment]
It's already implemented as `--timeout` option.
