### ISSUE TITLE
Horizon Support

### ISSUE THREAD

**Issue by zek** [nuwber/rabbitevents#99]
Does this package support horizon?

**Comment by masterjus** [comment]
@zek No. Could you please provide a use case? The RabbitEvents is not about queues.

**Comment by zek** [comment]
I'm running 100s of `rabbitevents:listen`. It's hard to maintain it. 
What I need is managing all workers with horizon and horizon metrics are very useful. I have multiple servers and each of them running multiple rabbit workers.

I'm using rabbitevents for months therefore I didn't want to change it. I'm very happy with using it however it lacks horizon and multiple connection support #98 

Btw following package supports horizon. Maybe you would ilke to check it 
https://github.com/vyuldashev/laravel-queue-rabbitmq

**Comment by masterjus** [comment]
Horizon works with Redis and this is the queue management. Maybe the RabbitMQ confuses you and you think that this is about a queue, but no, RabbitMQ is a good transporting tool for pub/sub as well.
